name: X1
description: Plugin de desafios 1v1
version: 1.0
main: me.marlon.x1.Main
author: Marlon_366
softdepend:
  - SimpleClans
  - CombatLog
  - Vault
commands:
  x1:
    description: Comando de desafios